### ISSUE TITLE
wrong region in cloudbuild-delivery.yaml file

### ISSUE THREAD

**Issue by gabriel131188** [GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild#10]
After performing the lab 2 times and support insisting on checking other points, I found that the error was just the region that was wrong, after changing:

_--region="us-central1"_

for

_--region="us-central1-b"_

the lab worked 100%.

Please, update the file "cloudbuild-delivery.yaml" in region.

Best Regards,
Gabriel D. Albuquerque

**Comment by MrTrustor** [comment]
Hi,

I think that the issue you are referring to was recently fixed with #9. Are you using the latest version of this repository?
If not, can you retry with the latest version?

Thank you

**Comment by gabriel131188** [comment]
Perfect, i did this lab "https://googlecourses.qwiklabs.com/course_sessions/520107/labs/102000", but now url doesnt open for me.

The git clone command should be pointing to a specific tag and not the most up-to-date one. Thanks for the quick feedback.

**Comment by gabriel131188** [comment]
The problem was in the course that performed the clone command by pointing out a tag where the region was missing the zone.
lab: https://googlecourses.qwiklabs.com/course_sessions/520107/labs/102000
