### ISSUE TITLE
Last step of cloudbuild-delivery.yaml fails

### ISSUE THREAD

**Issue by Ekenzy-101** [GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild#13]
These are the logs

```Already have image (with digest): gcr.io/cloud-builders/git
+ gcloud auth list --filter=status:ACTIVE --format=value(account)
+ git config user.email 165212509630@cloudbuild.gserviceaccount.com
+ git fetch origin master
From https://source.developers.google.com/p/hello-world-306210/r/gitops-env
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
+ git checkout master
Already on 'master'
+ git checkout d94e92224952c3d04cc508cb094c0ed9d1622ed8 kubernetes.yaml
Updated 0 paths from 687c017
+ git log --format=%B -n 1 d94e92224952c3d04cc508cb094c0ed9d1622ed8
+ git commit -m Manifest from commit d94e92224952c3d04cc508cb094c0ed9d1622ed8 Deploying image gcr.io/hello-world-306210/gitops:c760051
Built from commit c760051298b563cb506595998d70765c686c2a3d of repository gitops-app
Author: Emmanuel Onyekaba <ekeneonyekaba@gmail.com>
On branch master
nothing to commit, working tree clean
```

This is my last step 
```
- name: 'gcr.io/cloud-builders/git'
  id: Copy to master branch
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
    git fetch origin master && git checkout master && \
    git checkout $COMMIT_SHA kubernetes.yaml && \
    git commit -m "Manifest from commit $COMMIT_SHA $(git log --format=%B -n 1 $COMMIT_SHA)" && \
    git push origin master
```

**Comment by MrTrustor** [comment]
I'm sorry, what's the issue?

**Comment by Ekenzy-101** [comment]
![screenshot-console cloud google com-2021 11 22-18_00_53](https://user-images.githubusercontent.com/53738343/142903632-817272d7-da07-4262-ab51-fcd773f8e3e3.png)

**Comment by MrTrustor** [comment]
I think that you are trying to apply the exact same manifest as previously, hence there are no changes and git refuses to create an empty commit.

**Comment by Ekenzy-101** [comment]
The last step in the cloudbuild-delivery.yaml is not copying to kubernetes.yaml to the master branch. 
I tried deleting the kubernetes.yaml file in the master branch and reran the build it didn't copy. 

Please can you try it on your end?

**Comment by MrTrustor** [comment]
I ran through the [tutorial](https://cloud.google.com/kubernetes-engine/docs/tutorials/gitops-cloud-build) for which this repo was created just last week without any problem.

As I mentioned in my previous message, you have the following line in your logs:

```
+ git checkout d94e92224952c3d04cc508cb094c0ed9d1622ed8 kubernetes.yaml
Updated 0 paths from 687c017
```

This means that there is no difference between the kubernetes.yaml file in commit d94e922 (presumably on your candidate branch?) and the kubernetes.yaml file in your master branch. In other words, you are trying to redeploy exactly the same version of the app that's already running, and there are no changes to commit.

Also, I notice that you are using the master branch, whereas this repo is using a branch called "production" (see https://github.com/GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild/blob/9a57e4a7c8756f1cfaf020ba613ca9796ced62cc/cloudbuild-delivery.yaml#L48), not sure if that's part of the problem.

I really can't say more than that with the information I have.

**Comment by Ekenzy-101** [comment]
Hi MrTrustor. I redid the tutorial with the main branch name as master but it didn't work. I changed the main branch to production and it did works. Thank you for your help so far.

Do you have any idea why it didn't work on the master branch?

**Comment by MrTrustor** [comment]
No, sorry!
